// MW 5/1/2024: The skeleton for this code was generated by ChatGPT4 using the XAML view in the query

using CommunityToolkit.Mvvm.ComponentModel;
using CommunityToolkit.Mvvm.Input;
using System.Threading.Tasks;
using PostmanLibrary;

namespace AvaloniaPostman.ViewModels;

public partial class MainViewModel : ViewModelBase
{
    private readonly IApiAccess _api = new ApiAccess();

    // Property to bind with the API TextBox
    [ObservableProperty] private string apiUrl = "https://jsonplaceholder.typicode.com/todos";

    // Property to bind with the Results TextBox
    [ObservableProperty] private string results;

    // Property to bind with the Status TextBox
    [ObservableProperty] private string status = "Ready";

    // ICommand for the Go button
    [RelayCommand]
    private async Task ExecuteGoAsync()
    {
        Status = "Calling API...";
        Results = "";
        
        // Validate the APU URL
        if (_api.IsValidUrl(ApiUrl) == false)
        {
            Status = "Invalid URL";
            return;
        }

        try
        {
            Results = await _api.CallApiAsync(ApiUrl, true);
        }
        catch (System.Exception ex)
        {
            Results = $"Error: {ex.Message}";
        }
        finally
        {
            Status = "Ready";
        }
    }
}
